# Generated by Django 5.1.1 on 2024-09-09 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0007_alter_users_password_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password_modified_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 13, 9, 31, 270515)),
        ),
    ]
