# Generated by Django 5.1.1 on 2024-09-11 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0012_alter_users_password_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password_modified_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 11, 11, 9, 256132)),
        ),
    ]
