# Generated by Django 5.1.1 on 2024-09-07 04:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('join_date', models.DateTimeField()),
                ('role', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'constraints': [models.UniqueConstraint(fields=('username',), name='unique_username'), models.UniqueConstraint(fields=('email',), name='unique_email')],
            },
        ),
    ]
