# Generated by Django 5.1.1 on 2024-09-07 05:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('password_modified_at', models.DateTimeField()),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='auths', to='users.user')),
            ],
            options={
                'db_table': 'auth',
                'constraints': [models.UniqueConstraint(fields=('username',), name='unique_auth_username')],
            },
        ),
    ]
