# Generated by Django 5.1.1 on 2024-09-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auth',
        ),
    ]
