# Generated by Django 5.1.1 on 2024-09-08 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
        ('users', '0006_alter_user_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
