# Generated by Django 5.1.1 on 2024-09-08 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_auth_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='password_modified_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 17, 23, 24, 676355)),
        ),
    ]
