# Generated by Django 5.1.1 on 2024-09-11 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_story_image_alter_story_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 12, 27, 35, 397241)),
        ),
    ]
