# Generated by Django 5.1.1 on 2024-09-11 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_alter_story_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 15, 45, 17, 165767)),
        ),
    ]
