# Generated by Django 5.1.1 on 2024-09-12 05:03

import datetime
import story.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_alter_story_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 11, 3, 27, 943844)),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=story.models.generate_unique_filename),
        ),
    ]
